---
name: "DomIoT - Core"
description: "DomIoT Core is a core component of the DomIoT project, providing essential functionalities and services."
version: "0.0.1"
slug: "domiot_core"
init: false
panel_title: "DomIoT"
panel_icon: "mdi:account-supervisor-circle"
panel_admin: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
hassio_role: admin
hassio_api: true
homeassistant_api: true