---
name: "DomIoT - Core"
description: "DomIoT Core is a core component of the DomIoT project, providing essential functionalities and services."
version: "0.0.1"
slug: "domiot_core"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
hassio_role: admin
hassio_api: true
homeassistant_api: true

options:
  refresh_every_sec: 60
schema:
  refresh_every_sec: int